export interface Post {
  id: string;
  usuario_id: string;
  usuario_nome: string;
  usuario_avatar_url?: string | null;
  content: string;
  image_url?: string;
  media?: string[];
  reactions?: Record<string, number>;
  my_reaction?: string | null;
  likes: number;
  comments_count: number;
  liked_by_me?: boolean;
  created_at: string;
}

export interface InstaFlowComment {
  id: string;
  content: string;
  created_at: string;
  created_by: string;
  parent_id?: string | null;
  mention_user_ids?: string[];
  usuario_nome: string;
  usuario_avatar_url?: string | null;
  reactions?: Record<string, number>;
  my_reaction?: string | null;
  reactions_total?: number;
}

export interface Opportunity {
  id: string;
  title: string;
  value: number;
  status: 'Lead' | 'Contact' | 'Proposal' | 'Negotiation' | 'Closed';
  seller: string;
  created_at: string;
}

export interface Recognition {
  id: string;
  title: string;
  description?: string;
  user_id: string;
  user_nome?: string;
  created_by: string;
  created_at: string;
}

export interface CalendarEvent {
  id: string;
  task_id?: string;
  user_id: string;
  start_at: string;
  end_at: string;
  created_at: string;
}

export interface Notification {
  id: string;
  user_id: string;
  type: string;
  entity_type?: 'post' | 'task' | 'comment';
  entity_id?: string;
  title: string;
  message?: string;
  content?: string;
  link?: string;
  metadata?: any | null;
  is_read: boolean;
  created_at: string;
}

export interface ServicEquipamento {
  id: string;
  id_rst: string; // Generated by DB
  cod_proposta: string;
  cliente: string;
  cnpj?: string | null;
  endereco?: string | null;
  numero_nf?: string | null;
  numero_pedido?: string | null;
  modelo?: string | null;
  fabricante?: string | null;
  numero_serie?: string | null;
  numero_serie2?: string | null;
  tag?: string | null;
  garantia: boolean;
  faixa?: string | null;
  relatorio_tecnico?: string | null;
  anexos?: unknown | null;
  vendedor?: string | null;
  email_vendedor?: string | null;
  empresa_correspondente?: string | null;
  observacoes_equipamento?: string | null;
  imagens?: string[] | null;
  testes_realizados?: string | null;
  servicos_a_fazer?: string | null;
  numero_certificado?: string | null;
  data_calibracao?: string | null;
  data_entrada: string;
  data_finalizada?: string | null;
  fase: string; // Replaces 'status'
  responsavel?: string | null;
  solucao?: string | null;
  etapa_omie?: string | null;
  created_at: string;
  updated_at: string;
  data_fase_atual?: string;
}
